version: '3.8'

services:
  api-transacoes:
    build: 
      context: ./gastos-back
    ports:
      - "4000:4000"
    volumes:
      - sqlite_dados:/app
    networks:
      - rede_financas
    env_file:
      - ./gastos-back/.env

  frontend:
    build:
      context: ./gastos
    ports:
      - "8080:80"
    depends_on:
      - api-transacoes 
    networks:
      - rede_financas

volumes:
  sqlite_dados:

networks:
  rede_financas:
    driver: bridge